site_name: Conia Quma
copyright: © 2022 ebene fünf GmbH
nav:
  - index.md
theme:
    name: conia
repo_url: https://github.com/coniadev/quma
extra:
    project: Conia Quma
plugins:
    - search
    - macros:
        module_name: docs/main
markdown_extensions:
  - admonition
